// AUTO-GENERATED FILE - DO NOT EDIT BY HAND.
//
// Generated by embed_runtime.ps1 from the runtime C source:
//     include\gallt\runtime\crt.c
//     SHA-256: af119ec5dfe17bf8b1b95ad73aebe5c1f3ad0329f5743615e16582e2728da7c1

#ifndef GALLT_RUNTIME_CRT_EMBEDDED_HPP
#define GALLT_RUNTIME_CRT_EMBEDDED_HPP

namespace gallt {

    inline constexpr const char* kGalltRuntimeCSource = R"GALLT_CRT(
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <direct.h>

typedef struct gallt_string {
    int64_t length;
    int64_t capacity;
    union {
        char bytes[16];
        char* heap;
    } data;
} gallt_string;

static const char* gallt_string_data_ptr(const gallt_string* s) {
    return s->length <= 15 ? s->data.bytes : s->data.heap;
}

static void gallt_string_free_contents(gallt_string* s) {
    if (s->length > 15 && s->data.heap != NULL) {
        free(s->data.heap);
    }
    memset(s, 0, sizeof(*s));
}

static gallt_string gallt_string_from_bytes_impl(const char* data, int64_t len) {
    gallt_string result;
    memset(&result, 0, sizeof(result));
    result.length = len;
    if (len <= 15) {
        result.capacity = 16;
        if (len > 0) memcpy(result.data.bytes, data, (size_t)len);
        if (len < 16) result.data.bytes[len] = '\0';
        return result;
    }
    char* buffer = (char*)malloc((size_t)len + 1);
    if (buffer == NULL) {
        result.length = 0;
        result.capacity = 0;
        return result;
    }
    memcpy(buffer, data, (size_t)len);
    buffer[len] = '\0';
    result.capacity = len + 1;
    result.data.heap = buffer;
    return result;
}

void gallt_string_init(gallt_string* out, const char* data, int64_t len) {
    if (data == NULL || len < 0) len = 0;
    if (out != NULL) {
        *out = gallt_string_from_bytes_impl(data == NULL ? "" : data, len);
    }
}

void gallt_string_assign(gallt_string* dest, const gallt_string* src) {
    if (dest == NULL || src == NULL) return;
    gallt_string replacement = gallt_string_from_bytes_impl(
        gallt_string_data_ptr(src), src->length);
    gallt_string_free_contents(dest);
    *dest = replacement;
}

void gallt_string_destroy(gallt_string* s) {
    if (s != NULL) gallt_string_free_contents(s);
}

const char* gallt_string_cstr(const gallt_string* s) {
    if (s == NULL) return "";
    return gallt_string_data_ptr(s);
}

void gallt_string_concat(gallt_string* out, const gallt_string* a, const gallt_string* b) {
    if (out == NULL || a == NULL || b == NULL) return;
    int64_t total = a->length + b->length;
    char* temp = (char*)malloc((size_t)(total == 0 ? 1 : total));
    if (temp == NULL) {
        gallt_string_free_contents(out);
        return;
    }
    if (a->length > 0) memcpy(temp, gallt_string_data_ptr(a), (size_t)a->length);
    if (b->length > 0) memcpy(temp + a->length, gallt_string_data_ptr(b), (size_t)b->length);
    gallt_string replacement = gallt_string_from_bytes_impl(temp, total);
    free(temp);


    *out = replacement;
}

static int gallt_format_fp(double v, char* buffer, size_t size) {
    int n = snprintf(buffer, size, "%g", v);
    if (n < 0) return 0;
    if ((size_t)n + 2 >= size) return n;
    if (strpbrk(buffer, ".eEnNiI") == NULL) {
        buffer[n] = '.';
        buffer[n + 1] = '0';
        buffer[n + 2] = '\0';
        return n + 2;
    }
    return n;
}

void gallt_output_string(const gallt_string* s) {
    if (s == NULL) return;
    fwrite(gallt_string_data_ptr(s), 1, (size_t)s->length, stdout);
    fflush(stdout);
}

void gallt_output_i32(int32_t v) { printf("%d", (int)v); fflush(stdout); }
void gallt_output_u32(uint32_t v) { printf("%u", (unsigned)v); fflush(stdout); }
void gallt_output_i64(int64_t v) { printf("%lld", (long long)v); fflush(stdout); }
void gallt_output_u64(uint64_t v) { printf("%llu", (unsigned long long)v); fflush(stdout); }
void gallt_output_f32(float v) {
    char buffer[80];
    int n = gallt_format_fp((double)v, buffer, sizeof(buffer));
    fwrite(buffer, 1, (size_t)n, stdout);
    fflush(stdout);
}
void gallt_output_f64(double v) {
    char buffer[80];
    int n = gallt_format_fp(v, buffer, sizeof(buffer));
    fwrite(buffer, 1, (size_t)n, stdout);
    fflush(stdout);
}
void gallt_output_char(char v) { putchar((unsigned char)v); fflush(stdout); }
void gallt_output_bool(unsigned char v) { fputs(v ? "true" : "false", stdout); fflush(stdout); }
void gallt_output_ptr(const void* v) { printf("%p", v); fflush(stdout); }

void gallt_input_i32(int32_t* p) { if (scanf("%d", p) != 1 && p) *p = 0; }
void gallt_input_u32(uint32_t* p) { if (scanf("%u", p) != 1 && p) *p = 0; }
void gallt_input_i64(int64_t* p) { if (scanf("%lld", (long long*)p) != 1 && p) *p = 0; }
void gallt_input_u64(uint64_t* p) { if (scanf("%llu", (unsigned long long*)p) != 1 && p) *p = 0; }
void gallt_input_uchar(unsigned char* p) { if (scanf(" %c", (char*)p) != 1 && p) *p = 0; }
void gallt_input_f32(float* p) { if (scanf("%f", p) != 1 && p) *p = 0; }
void gallt_input_f64(double* p) { if (scanf("%lf", p) != 1 && p) *p = 0; }
void gallt_input_char(char* p) { if (scanf(" %c", p) != 1 && p) *p = 0; }
void gallt_input_bool(unsigned char* p) {
    int v = 0;
    if (scanf("%d", &v) != 1) v = 0;
    if (p) *p = v ? 1 : 0;
}

void gallt_input_string(gallt_string* p) {
    if (p == NULL) return;
    char buffer[8192];
    if (fgets(buffer, (int)sizeof(buffer), stdin) == NULL) buffer[0] = '\0';
    buffer[sizeof(buffer) - 1] = '\0';
    size_t len = strlen(buffer);
    while (len > 0 && (buffer[len - 1] == '\n' || buffer[len - 1] == '\r')) {
        buffer[--len] = '\0';
    }
    gallt_string replacement = gallt_string_from_bytes_impl(buffer, (int64_t)len);
    gallt_string_free_contents(p);
    *p = replacement;
}

static gallt_string gallt_string_from_int64(int64_t v) {
    char buffer[64];
    int n = snprintf(buffer, sizeof(buffer), "%lld", (long long)v);
    return gallt_string_from_bytes_impl(buffer, n < 0 ? 0 : n);
}

void gallt_string_from_i32(gallt_string* out, int32_t v) {
    if (out != NULL) *out = gallt_string_from_int64(v);
}
void gallt_string_from_u32(gallt_string* out, uint32_t v) {
    if (out == NULL) return;
    char buffer[64];
    int n = snprintf(buffer, sizeof(buffer), "%u", (unsigned)v);
    *out = gallt_string_from_bytes_impl(buffer, n < 0 ? 0 : n);
}
void gallt_string_from_i64(gallt_string* out, int64_t v) {
    if (out != NULL) *out = gallt_string_from_int64(v);
}
void gallt_string_from_u64(gallt_string* out, uint64_t v) {
    if (out == NULL) return;
    char buffer[64];
    int n = snprintf(buffer, sizeof(buffer), "%llu", (unsigned long long)v);
    *out = gallt_string_from_bytes_impl(buffer, n < 0 ? 0 : n);
}
void gallt_string_from_char(gallt_string* out, char v) {
    if (out != NULL) *out = gallt_string_from_bytes_impl(&v, 1);
}
void gallt_string_from_bool(gallt_string* out, unsigned char v) {
    if (out == NULL) return;
    *out = v ? gallt_string_from_bytes_impl("true", 4)
             : gallt_string_from_bytes_impl("false", 5);
}
void gallt_string_from_f32(gallt_string* out, float v) {
    if (out == NULL) return;
    char buffer[64];
    int n = gallt_format_fp((double)v, buffer, sizeof(buffer));
    *out = gallt_string_from_bytes_impl(buffer, n < 0 ? 0 : n);
}
void gallt_string_from_f64(gallt_string* out, double v) {
    if (out == NULL) return;
    char buffer[64];
    int n = gallt_format_fp(v, buffer, sizeof(buffer));
    *out = gallt_string_from_bytes_impl(buffer, n < 0 ? 0 : n);
}
void* gallt_alloc_bytes(int64_t size) {
    if (size <= 0) size = 1;
    return calloc(1, (size_t)size);
}
void gallt_free_ptr(void* ptr) {
    free(ptr);
}
void gallt_check_fptr(void* fn) {
    if (fn == NULL) {
        fprintf(stderr, "RTER 0002: null function pointer call\n");
        exit(1);
    }
}

typedef struct gallt_file {
    FILE* fp;

    int error;
    int eof;
    struct gallt_file* next;
    void* slot;
} gallt_file;

typedef void* gallt_file_slot;

static gallt_file* gallt_file_registry = NULL;
static int gallt_file_exit_registered = 0;

static void gallt_file_release_all(void) {
    gallt_file* h = gallt_file_registry;
    while (h != NULL) {
        gallt_file* next = h->next;
        if (h->fp != NULL) {
            fclose(h->fp);
            h->fp = NULL;
        }
        free(h->slot);
        free(h);
        h = next;
    }
    gallt_file_registry = NULL;
}

static void gallt_file_register(gallt_file* handle) {
    handle->next = gallt_file_registry;
    gallt_file_registry = handle;
    if (!gallt_file_exit_registered) {
        atexit(gallt_file_release_all);
        gallt_file_exit_registered = 1;
    }
}

static gallt_file* gallt_file_deref(void* slot) {
    if (slot == NULL) return NULL;
    return *(gallt_file**)slot;
}

static int gallt_errno_code(void) {
    switch (errno) {
    case ENOENT: return 3;
    case EACCES:
    case EPERM:  return 2;
    case EEXIST: return 4;
    case ENOSPC: return 8;
    default:     return 9;
    }
}

static void gallt_file_set_error(gallt_file* handle, int code) {
    if (handle != NULL) handle->error = code;
}

static char* gallt_cstr_from_string(const gallt_string* s) {
    int64_t len = (s == NULL) ? 0 : s->length;
    if (len < 0) len = 0;
    char* buffer = (char*)malloc((size_t)len + 1);
    if (buffer == NULL) return NULL;
    if (len > 0) memcpy(buffer, gallt_string_data_ptr(s), (size_t)len);
    buffer[len] = '\0';
    return buffer;
}

static gallt_file* gallt_file_valid(void* slot) {
    gallt_file* h = gallt_file_deref(slot);
    if (h == NULL || h->fp == NULL) {
        gallt_file_set_error(h, 1);
        return NULL;
    }
    return h;
}

static int gallt_valid_file_mode(const char* mode) {
    static const char* valid_modes[] = {
        "r", "w", "a", "r+", "w+", "a+",
        "rb", "wb", "ab", "r+b", "w+b", "a+b",
    };
    if (mode == NULL) return 0;
    for (size_t i = 0; i < sizeof(valid_modes) / sizeof(valid_modes[0]); ++i) {
        if (strcmp(mode, valid_modes[i]) == 0) return 1;
    }
    return 0;
}

void* gallt_file_open(const gallt_string* path, const gallt_string* mode) {
    if (path == NULL || mode == NULL) return NULL;
    char* path_cstr = gallt_cstr_from_string(path);
    char* mode_cstr = gallt_cstr_from_string(mode);
    if (path_cstr == NULL || mode_cstr == NULL) {
        free(path_cstr);
        free(mode_cstr);
        return NULL;
    }
    if (!gallt_valid_file_mode(mode_cstr)) {
        free(path_cstr);
        free(mode_cstr);
        return NULL;
    }

    char open_mode[8];
    size_t mi = 0;
    while (mode_cstr[mi] != '\0' && mi + 1 < sizeof(open_mode)) {
        open_mode[mi] = mode_cstr[mi];
        ++mi;
    }
    open_mode[mi] = '\0';
    if (strchr(open_mode, 'b') == NULL && mi + 1 < sizeof(open_mode)) {
        open_mode[mi] = 'b';
        open_mode[mi + 1] = '\0';
    }
    FILE* fp = fopen(path_cstr, open_mode);
    free(path_cstr);
    free(mode_cstr);
    if (fp == NULL) return NULL;
    gallt_file* handle = (gallt_file*)calloc(1, sizeof(gallt_file));
    if (handle == NULL) {
        fclose(fp);
        return NULL;
    }
    gallt_file_slot* slot = (gallt_file_slot*)calloc(1, sizeof(gallt_file_slot));
    if (slot == NULL) {
        fclose(fp);
        free(handle);
        return NULL;
    }
    *slot = handle;
    handle->fp = fp;
    handle->error = 0;
    handle->eof = 0;
    handle->slot = slot;
    gallt_file_register(handle);
    return slot;
}

int8_t gallt_file_close(void* slot) {
    gallt_file* h = gallt_file_deref(slot);
    if (h == NULL || h->fp == NULL) return 0;
    FILE* fp = h->fp;
    h->fp = NULL;
    int rc = fclose(fp);
    h->error = (rc == 0) ? 0 : gallt_errno_code();
    *(gallt_file**)slot = NULL;
    int ok = (rc == 0) ? 1 : 0;
    return (int8_t)ok;
}

int8_t gallt_file_flush(void* handle) {
    gallt_file* h = gallt_file_valid(handle);
    if (h == NULL) return 0;
    if (fflush(h->fp) != 0) {
        gallt_file_set_error(h, 6);
        return 0;
    }
    h->error = 0;
    return 1;
}

int32_t gallt_file_read(void* handle, void* buffer, int32_t count) {
    gallt_file* h = gallt_file_valid(handle);
    if (h == NULL) return -1;
    if (buffer == NULL || count < 0) {
        gallt_file_set_error(h, 5);
        return -1;
    }
    size_t want = (size_t)count;
    size_t got = fread(buffer, 1, want, h->fp);
    h->eof = feof(h->fp) ? 1 : 0;
    if (got < want && ferror(h->fp)) {
        gallt_file_set_error(h, 5);
        return -1;
    }
    h->error = 0;
    return (int32_t)got;
}

int32_t gallt_file_write(void* handle, const gallt_string* s) {
    gallt_file* h = gallt_file_valid(handle);
    if (h == NULL) return -1;
    if (s == NULL) {
        gallt_file_set_error(h, 6);
        return -1;
    }
    int64_t len = s->length;
    if (len <= 0) {
        h->error = 0;
        return 0;
    }
    size_t written = fwrite(gallt_string_data_ptr(s), 1, (size_t)len, h->fp);
    if (written != (size_t)len) {
        gallt_file_set_error(h, errno == ENOSPC ? 8 : 6);
        return -1;
    }
    h->error = 0;
    return (int32_t)written;
}

int32_t gallt_file_write_bytes(void* handle, const void* buffer, int32_t count) {
    gallt_file* h = gallt_file_valid(handle);
    if (h == NULL) return -1;
    if (buffer == NULL || count < 0) {
        gallt_file_set_error(h, 6);
        return -1;
    }
    if (count == 0) {
        h->error = 0;
        return 0;
    }
    size_t written = fwrite(buffer, 1, (size_t)count, h->fp);
    if (written != (size_t)count) {
        gallt_file_set_error(h, errno == ENOSPC ? 8 : 6);
        return -1;
    }
    h->error = 0;
    return (int32_t)written;
}

int32_t gallt_file_getc(void* handle) {
    gallt_file* h = gallt_file_valid(handle);
    if (h == NULL) return -1;
    int c = fgetc(h->fp);
    if (c == EOF) {
        h->eof = 1;
        h->error = ferror(h->fp) ? 5 : 0;
        return -1;
    }
    h->error = 0;
    return (int32_t)(c & 0xFF);
}

int32_t gallt_file_putc(void* handle, int32_t ch) {
    gallt_file* h = gallt_file_valid(handle);
    if (h == NULL) return -1;
    int c = fputc(ch & 0xFF, h->fp);
    if (c == EOF) {
        gallt_file_set_error(h, errno == ENOSPC ? 8 : 6);
        return -1;
    }
    h->error = 0;
    return (int32_t)(c & 0xFF);
}

void gallt_file_readline(gallt_string* out, void* handle) {
    if (out == NULL) return;
    gallt_file* h = gallt_file_valid(handle);
    if (h == NULL) {
        *out = gallt_string_from_bytes_impl("", 0);
        return;
    }
    char* buffer = NULL;
    size_t capacity = 0;
    size_t length = 0;
    int c = EOF;
    while ((c = fgetc(h->fp)) != EOF) {
        if (c == '\n') break;
        if (length + 1 > capacity) {
            size_t next = (capacity == 0) ? 128 : capacity * 2;
            char* grown = (char*)realloc(buffer, next);
            if (grown == NULL) break;
            buffer = grown;
            capacity = next;
        }
        buffer[length++] = (char)c;
    }
    if (c == EOF) h->eof = 1;
    if (length > 0 && buffer != NULL && buffer[length - 1] == '\r') length--;
    if (buffer == NULL) {
        *out = gallt_string_from_bytes_impl("", 0);
    } else {
        *out = gallt_string_from_bytes_impl(buffer, (int64_t)length);
        free(buffer);
    }
    h->error = 0;
}

int32_t gallt_file_writeline(void* handle, const gallt_string* s) {
    gallt_file* h = gallt_file_valid(handle);
    if (h == NULL) return -1;
    int64_t len = (s == NULL) ? 0 : s->length;
    size_t written = 0;
    if (len > 0) {
        written = fwrite(gallt_string_data_ptr(s), 1, (size_t)len, h->fp);
        if (written != (size_t)len) {
            gallt_file_set_error(h, errno == ENOSPC ? 8 : 6);
            return -1;
        }
    }
    if (fputc('\n', h->fp) == EOF) {
        gallt_file_set_error(h, errno == ENOSPC ? 8 : 6);
        return -1;
    }
    h->error = 0;
    return (int32_t)(written + 1);
}

int8_t gallt_file_seek(void* handle, int32_t offset, int32_t origin) {
    gallt_file* h = gallt_file_valid(handle);
    if (h == NULL) return 0;
    int whence = SEEK_SET;
    switch (origin) {
    case 0: whence = SEEK_SET; break;
    case 1: whence = SEEK_CUR; break;
    case 2: whence = SEEK_END; break;
    default:
        gallt_file_set_error(h, 7);
        return 0;
    }
    if (fseek(h->fp, (long)offset, whence) != 0) {
        gallt_file_set_error(h, 7);
        return 0;
    }
    h->eof = 0;
    h->error = 0;
    return 1;
}

int32_t gallt_file_tell(void* handle) {
    gallt_file* h = gallt_file_valid(handle);
    if (h == NULL) return -1;
    long pos = ftell(h->fp);
    if (pos < 0) {
        gallt_file_set_error(h, 7);
        return -1;
    }
    h->error = 0;
    return (int32_t)pos;
}

int8_t gallt_file_eof(void* handle) {
    gallt_file* h = gallt_file_valid(handle);
    if (h == NULL) return 0;
    if (h->eof || feof(h->fp)) return 1;
    return 0;
}

int32_t gallt_file_error(void* slot) {
    gallt_file* h = gallt_file_deref(slot);
    if (h == NULL || h->fp == NULL) return 1;
    return h->error;
}

int8_t gallt_file_remove(const gallt_string* path) {
    char* p = gallt_cstr_from_string(path);
    if (p == NULL) return 0;
    int rc = remove(p);
    free(p);
    return (int8_t)(rc == 0 ? 1 : 0);
}

int8_t gallt_file_rename(const gallt_string* from, const gallt_string* to) {
    char* a = gallt_cstr_from_string(from);
    char* b = gallt_cstr_from_string(to);
    if (a == NULL || b == NULL) {
        free(a);
        free(b);
        return 0;
    }
    int rc = rename(a, b);
    free(a);
    free(b);
    return (int8_t)(rc == 0 ? 1 : 0);
}

int8_t gallt_file_exists(const gallt_string* path) {
    char* p = gallt_cstr_from_string(path);
    if (p == NULL) return 0;
    FILE* fp = fopen(p, "rb");
    if (fp != NULL) {
        fclose(fp);
        free(p);
        return 1;
    }
    free(p);
    return 0;
}

int32_t gallt_file_size(const gallt_string* path) {
    char* p = gallt_cstr_from_string(path);
    if (p == NULL) return -1;
    FILE* fp = fopen(p, "rb");
    if (fp == NULL) {
        free(p);
        return -1;
    }
    free(p);
    if (fseek(fp, 0, SEEK_END) != 0) {
        fclose(fp);
        return -1;
    }
    long size = ftell(fp);
    fclose(fp);
    if (size < 0) return -1;
    return (int32_t)size;
}

int8_t gallt_file_copy(const gallt_string* from, const gallt_string* to) {
    char* a = gallt_cstr_from_string(from);
    char* b = gallt_cstr_from_string(to);
    if (a == NULL || b == NULL) {
        free(a);
        free(b);
        return 0;
    }
    FILE* in = fopen(a, "rb");
    if (in == NULL) {
        free(a);
        free(b);
        return 0;
    }
    FILE* out = fopen(b, "wb");
    if (out == NULL) {
        fclose(in);
        free(a);
        free(b);
        return 0;
    }
    char chunk[8192];
    size_t n = 0;
    int ok = 1;
    while ((n = fread(chunk, 1, sizeof(chunk), in)) > 0) {
        if (fwrite(chunk, 1, n, out) != n) {
            ok = 0;
            break;
        }
    }
    if (ferror(in)) ok = 0;
    fclose(in);
    if (fclose(out) != 0) ok = 0;
    free(a);
    free(b);
    return (int8_t)(ok ? 1 : 0);
}

int8_t gallt_file_mkdir(const gallt_string* path) {
    char* p = gallt_cstr_from_string(path);
    if (p == NULL) return 0;
    int rc = _mkdir(p);
    free(p);
    return (int8_t)(rc == 0 ? 1 : 0);
}

int8_t gallt_file_removedir(const gallt_string* path) {
    char* p = gallt_cstr_from_string(path);
    if (p == NULL) return 0;
    int rc = _rmdir(p);
    free(p);
    return (int8_t)(rc == 0 ? 1 : 0);
}
)GALLT_CRT";

}

#endif
